### ISSUE TITLE
执行任务admin端报错：java.net.MalformedURLException: no protocol: 192.168.0.105:8083/run

### ISSUE THREAD

**Issue by yejc** [feixiaobo/go-xxl-job-client#6]
xxl-job版本：v2.2.0
go-client版本：v2.0.3

**Comment by jiangjianyong** [comment]
Use the [xxl-job-executor-go](github.com/xxl-job/xxl-job-executor-go)

**Comment by yejc** [comment]
> Use the [xxl-job-executor-go](github.com/xxl-job/xxl-job-executor-go)

404？

**Comment by feixiaobo** [comment]
v2.2版本将通信协议从rpc改成了http, 我还在支持中，预计本周可以支持v2.2

**Comment by jiangjianyong** [comment]
> > Use the [xxl-job-executor-go](https://github.com/xxl-job/xxl-job-executor-go)
> 
> 404？
https://github.com/xxl-job/xxl-job-executor-go

**Comment by feixiaobo** [comment]
已兼容新版本
